name: PreventPlayerDrop
version: '${project.version}'
main: org.snorklingturtle.preventplayerdrop.PreventPlayerDrop
api-version: '1.21'
commands:
  preserve:
    description: Toggle preserving on / off